"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { deletePayment, getPayments } from "@/lib/api";

type Payment = { payment_id: number; booking_id: number; amount: number; payment_method: string; payment_status: string; transaction_id: string; payment_date: string | null };

export default function PaymentsPage() {
  const [payments, setPayments] = useState<Payment[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [deletingId, setDeletingId] = useState<number | null>(null);
  async function loadPayments() { try { const data = await getPayments(); setError(""); setPayments(data); } catch (err) { setError(err instanceof Error ? err.message : "Failed to fetch payments."); } finally { setLoading(false); } }
  useEffect(() => { getPayments().then((data) => { setError(""); setPayments(data); }).catch((err) => setError(err instanceof Error ? err.message : "Failed to fetch payments.")).finally(() => setLoading(false)); }, []);
  async function handleDelete(payment: Payment) { if (!window.confirm("Are you sure you want to delete this payment?")) return; setDeletingId(payment.payment_id); setError(""); try { await deletePayment(String(payment.payment_id)); await loadPayments(); } catch (err) { setError(err instanceof Error ? err.message : "Failed to delete payment."); } finally { setDeletingId(null); } }
  return <div className="page-container"><div className="page-header" style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}><div><h1 className="page-title">Payments</h1><p className="page-description">Manage booking payments.</p></div><Link href="/payments/new" className="primary-button" style={{ textDecoration: "none", display: "inline-block" }}>+ New Payment</Link></div><div className="table-container"><div className="table-header">All Payments</div><table><thead><tr><th>Payment ID</th><th>Booking ID</th><th>Amount</th><th>Method</th><th>Status</th><th>Transaction ID</th><th>Payment Date</th><th>Actions</th></tr></thead><tbody>{loading ? <tr><td colSpan={8}>Loading payments...</td></tr> : payments.length === 0 ? <tr><td colSpan={8}>No payments found.</td></tr> : payments.map((payment) => <tr key={payment.payment_id}><td>{payment.payment_id}</td><td>{payment.booking_id}</td><td>{payment.amount}</td><td>{payment.payment_method}</td><td>{payment.payment_status}</td><td><Link href={`/payments/${payment.payment_id}`} style={{ color: "#2563eb", textDecoration: "none", fontWeight: 600 }}>{payment.transaction_id}</Link></td><td>{payment.payment_date ?? "Not set"}</td><td><Link href={`/payments/${payment.payment_id}`} style={{ marginRight: "12px", color: "#2563eb", textDecoration: "none" }}>View</Link><Link href={`/payments/edit/${payment.payment_id}`} style={{ color: "#16a34a", textDecoration: "none" }}>Edit</Link><button type="button" onClick={() => handleDelete(payment)} disabled={deletingId === payment.payment_id} style={{ marginLeft: "12px", border: "none", background: "transparent", color: "#dc2626", cursor: deletingId === payment.payment_id ? "not-allowed" : "pointer", fontSize: "13px" }}>{deletingId === payment.payment_id ? "Deleting..." : "Delete"}</button></td></tr>)}</tbody></table>{error && <div style={{ padding: "14px 20px", color: "#b91c1c", background: "#fee2e2" }}>{error}</div>}</div></div>;
}
