"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createRating, getBookings, getEmployers, getWorkers } from "@/lib/api";

export type RatingFormData = { booking_id: string; employer_id: string; worker_id: string; rating: string; review: string };
export type BookingOption = { booking_id: number; job_id: number; worker_id: number; scheduled_date: string };
export type EmployerOption = { employer_id: number; full_name: string };
export type WorkerOption = { worker_id: number; full_name: string };

export default function NewRatingPage() {
  const router = useRouter(); const [formData, setFormData] = useState<RatingFormData>({ booking_id: "", employer_id: "", worker_id: "", rating: "5", review: "" }); const [bookings, setBookings] = useState<BookingOption[]>([]); const [employers, setEmployers] = useState<EmployerOption[]>([]); const [workers, setWorkers] = useState<WorkerOption[]>([]); const [loadingOptions, setLoadingOptions] = useState(true); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  useEffect(() => { Promise.all([getBookings(), getEmployers(), getWorkers()]).then(([bookingsData, employersData, workersData]) => { setBookings(bookingsData); setEmployers(employersData); setWorkers(workersData); }).catch((err) => setError(err instanceof Error ? err.message : "Failed to load rating options.")).finally(() => setLoadingOptions(false)); }, []);
  function handleChange(event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) { const { name, value } = event.target; setFormData((current) => ({ ...current, [name]: value })); }
  async function handleSubmit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); try { await createRating({ booking_id: Number(formData.booking_id), employer_id: Number(formData.employer_id), worker_id: Number(formData.worker_id), rating: Number(formData.rating), review: formData.review || null }); router.push("/ratings"); } catch (err) { setError(err instanceof Error ? err.message : "Failed to create rating."); } finally { setLoading(false); } }
  if (loadingOptions) return <div className="page-container">Loading bookings, employers, and workers...</div>;
  return <RatingForm title="Add New Rating" description="Record feedback for a booking." formData={formData} bookings={bookings} employers={employers} workers={workers} error={error} loading={loading} submitLabel="Create Rating" onChange={handleChange} onSubmit={handleSubmit} />;
}

export function RatingForm({ title, description, formData, bookings, employers, workers, error, loading, submitLabel, onChange, onSubmit }: { title: string; description: string; formData: RatingFormData; bookings: BookingOption[]; employers: EmployerOption[]; workers: WorkerOption[]; error: string; loading: boolean; submitLabel: string; onChange: (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => void; onSubmit: (event: React.FormEvent<HTMLFormElement>) => void }) {
  const inputStyle = { width: "100%", padding: "11px", border: "1px solid #d1d5db", borderRadius: "7px" }; const fieldStyle = { marginBottom: "20px" }; const labelStyle = { display: "block", marginBottom: "7px", fontWeight: 600 } as const;
  return <div className="page-container"><div className="page-header"><h1 className="page-title">{title}</h1><p className="page-description">{description}</p></div><div className="table-container"><div className="table-header">Rating Information</div><form onSubmit={onSubmit} style={{ padding: "25px" }}><div style={fieldStyle}><label htmlFor="booking_id" style={labelStyle}>Booking</label><select id="booking_id" name="booking_id" value={formData.booking_id} onChange={onChange} required style={inputStyle}><option value="">Select a booking</option>{bookings.map((booking) => <option key={booking.booking_id} value={booking.booking_id}>Booking #{booking.booking_id} - Job #{booking.job_id} - Scheduled: {booking.scheduled_date}</option>)}</select></div><div style={fieldStyle}><label htmlFor="employer_id" style={labelStyle}>Employer</label><select id="employer_id" name="employer_id" value={formData.employer_id} onChange={onChange} required style={inputStyle}><option value="">Select an employer</option>{employers.map((employer) => <option key={employer.employer_id} value={employer.employer_id}>{employer.full_name} - ID {employer.employer_id}</option>)}</select></div><div style={fieldStyle}><label htmlFor="worker_id" style={labelStyle}>Worker</label><select id="worker_id" name="worker_id" value={formData.worker_id} onChange={onChange} required style={inputStyle}><option value="">Select a worker</option>{workers.map((worker) => <option key={worker.worker_id} value={worker.worker_id}>{worker.full_name} - ID {worker.worker_id}</option>)}</select></div><div style={fieldStyle}><label htmlFor="rating" style={labelStyle}>Rating</label><select id="rating" name="rating" value={formData.rating} onChange={onChange} style={inputStyle}>{[1, 2, 3, 4, 5].map((score) => <option key={score} value={score}>{score}</option>)}</select></div><div style={fieldStyle}><label htmlFor="review" style={labelStyle}>Review</label><textarea id="review" name="review" value={formData.review} onChange={onChange} rows={4} style={inputStyle} /></div>{error && <div style={{ marginBottom: "20px", padding: "12px", background: "#fee2e2", color: "#b91c1c", borderRadius: "7px" }}>{error}</div>}<button type="submit" className="primary-button" disabled={loading}>{loading ? "Saving..." : submitLabel}</button></form></div></div>;
}
