"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createPayment, getBookings } from "@/lib/api";

export type PaymentFormData = { booking_id: string; amount: string; payment_method: string; payment_status: string; transaction_id: string };
export type BookingOption = { booking_id: number; job_id: number; worker_id: number; scheduled_date: string };

export default function NewPaymentPage() {
  const router = useRouter(); const [formData, setFormData] = useState<PaymentFormData>({ booking_id: "", amount: "", payment_method: "UPI", payment_status: "Pending", transaction_id: "" }); const [bookings, setBookings] = useState<BookingOption[]>([]); const [loadingBookings, setLoadingBookings] = useState(true); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  useEffect(() => { getBookings().then(setBookings).catch((err) => setError(err instanceof Error ? err.message : "Failed to load bookings.")).finally(() => setLoadingBookings(false)); }, []);
  function handleChange(event: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) { const { name, value } = event.target; setFormData((current) => ({ ...current, [name]: value })); }
  async function handleSubmit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); try { await createPayment({ booking_id: Number(formData.booking_id), amount: Number(formData.amount), payment_method: formData.payment_method, payment_status: formData.payment_status, transaction_id: formData.transaction_id }); router.push("/payments"); } catch (err) { setError(err instanceof Error ? err.message : "Failed to create payment."); } finally { setLoading(false); } }
  if (loadingBookings) return <div className="page-container">Loading bookings...</div>;
  return <PaymentForm title="Add New Payment" description="Record a payment for a booking." formData={formData} bookings={bookings} error={error} loading={loading} submitLabel="Create Payment" onChange={handleChange} onSubmit={handleSubmit} />;
}

export function PaymentForm({ title, description, formData, bookings, error, loading, submitLabel, onChange, onSubmit }: { title: string; description: string; formData: PaymentFormData; bookings: BookingOption[]; error: string; loading: boolean; submitLabel: string; onChange: (event: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => void; onSubmit: (event: React.FormEvent<HTMLFormElement>) => void }) {
  const inputStyle = { width: "100%", padding: "11px", border: "1px solid #d1d5db", borderRadius: "7px" }; const fieldStyle = { marginBottom: "20px" }; const labelStyle = { display: "block", marginBottom: "7px", fontWeight: 600 } as const;
  return <div className="page-container"><div className="page-header"><h1 className="page-title">{title}</h1><p className="page-description">{description}</p></div><div className="table-container"><div className="table-header">Payment Information</div><form onSubmit={onSubmit} style={{ padding: "25px" }}><div style={fieldStyle}><label htmlFor="booking_id" style={labelStyle}>Booking</label><select id="booking_id" name="booking_id" value={formData.booking_id} onChange={onChange} required style={inputStyle}><option value="">Select a booking</option>{bookings.map((booking) => <option key={booking.booking_id} value={booking.booking_id}>Booking {booking.booking_id} - Job {booking.job_id} - Worker {booking.worker_id} - {booking.scheduled_date}</option>)}</select></div><div style={fieldStyle}><label htmlFor="amount" style={labelStyle}>Amount</label><input id="amount" name="amount" type="number" min="0" step="0.01" value={formData.amount} onChange={onChange} required style={inputStyle} /></div><div style={fieldStyle}><label htmlFor="payment_method" style={labelStyle}>Payment Method</label><select id="payment_method" name="payment_method" value={formData.payment_method} onChange={onChange} style={inputStyle}><option value="UPI">UPI</option><option value="Credit Card">Credit Card</option><option value="Debit Card">Debit Card</option><option value="Cash">Cash</option><option value="Net Banking">Net Banking</option></select></div><div style={fieldStyle}><label htmlFor="payment_status" style={labelStyle}>Payment Status</label><select id="payment_status" name="payment_status" value={formData.payment_status} onChange={onChange} style={inputStyle}><option value="Paid">Paid</option><option value="Pending">Pending</option><option value="Refunded">Refunded</option></select></div><div style={fieldStyle}><label htmlFor="transaction_id" style={labelStyle}>Transaction ID</label><input id="transaction_id" name="transaction_id" value={formData.transaction_id} onChange={onChange} required style={inputStyle} /></div>{error && <div style={{ marginBottom: "20px", padding: "12px", background: "#fee2e2", color: "#b91c1c", borderRadius: "7px" }}>{error}</div>}<button type="submit" className="primary-button" disabled={loading}>{loading ? "Saving..." : submitLabel}</button></form></div></div>;
}
